-- Generated word pair seed
insert into public.word_pairs (id, category, civilian_word, undercover_word, difficulty, language, active)
values
('wp_001', 'Đồ ăn', 'Phở', 'Bún bò', 'easy', 'vi', true),
('wp_002', 'Đồ ăn', 'Pizza', 'Hamburger', 'easy', 'vi', true),
('wp_003', 'Đồ ăn', 'Bánh mì', 'Bánh bao', 'easy', 'vi', true),
('wp_004', 'Đồ ăn', 'Cơm tấm', 'Cơm gà', 'easy', 'vi', true),
('wp_005', 'Đồ ăn', 'Gỏi cuốn', 'Chả giò', 'easy', 'vi', true),
('wp_006', 'Đồ ăn', 'Sushi', 'Sashimi', 'medium', 'vi', true),
('wp_007', 'Đồ ăn', 'Lẩu', 'Nướng', 'easy', 'vi', true),
('wp_008', 'Đồ ăn', 'Bánh xèo', 'Bánh khọt', 'medium', 'vi', true),
('wp_009', 'Đồ uống', 'Cà phê', 'Trà sữa', 'easy', 'vi', true),
('wp_010', 'Đồ uống', 'Trà đá', 'Nước mía', 'easy', 'vi', true),
('wp_011', 'Đồ uống', 'Bia', 'Rượu', 'easy', 'vi', true),
('wp_012', 'Đồ uống', 'Nước dừa', 'Sinh tố', 'easy', 'vi', true),
('wp_013', 'Đồ uống', 'Matcha', 'Cacao', 'medium', 'vi', true),
('wp_014', 'Công nghệ', 'iPhone', 'Samsung', 'easy', 'vi', true),
('wp_015', 'Công nghệ', 'MacBook', 'Laptop Windows', 'easy', 'vi', true),
('wp_016', 'Công nghệ', 'AirPods', 'Tai nghe Bluetooth', 'easy', 'vi', true),
('wp_017', 'Công nghệ', 'TikTok', 'Instagram', 'easy', 'vi', true),
('wp_018', 'Công nghệ', 'Zalo', 'Messenger', 'easy', 'vi', true),
('wp_019', 'Công nghệ', 'ChatGPT', 'Google', 'medium', 'vi', true),
('wp_020', 'Giải trí', 'Netflix', 'YouTube', 'easy', 'vi', true),
('wp_021', 'Giải trí', 'Karaoke', 'Bar', 'easy', 'vi', true),
('wp_022', 'Giải trí', 'Game online', 'Board game', 'medium', 'vi', true),
('wp_023', 'Giải trí', 'Phim chiếu rạp', 'Phim Netflix', 'easy', 'vi', true),
('wp_024', 'Giải trí', 'K-pop', 'V-pop', 'medium', 'vi', true),
('wp_025', 'Di chuyển', 'Grab', 'Taxi', 'easy', 'vi', true),
('wp_026', 'Di chuyển', 'Xe máy', 'Xe đạp', 'easy', 'vi', true),
('wp_027', 'Di chuyển', 'Máy bay', 'Tàu hỏa', 'easy', 'vi', true),
('wp_028', 'Di chuyển', 'Xe buýt', 'Xe khách', 'easy', 'vi', true),
('wp_029', 'Di chuyển', 'Tàu điện', 'Xe ôm', 'medium', 'vi', true),
('wp_030', 'Đời sống', 'Chợ', 'Siêu thị', 'easy', 'vi', true),
('wp_031', 'Đời sống', 'ATM', 'Ví MoMo', 'easy', 'vi', true),
('wp_032', 'Đời sống', 'Điều hòa', 'Quạt máy', 'easy', 'vi', true),
('wp_033', 'Đời sống', 'Gối', 'Chăn', 'easy', 'vi', true),
('wp_034', 'Đời sống', 'Dù', 'Áo mưa', 'easy', 'vi', true),
('wp_035', 'Đời sống', 'Nồi cơm điện', 'Lò vi sóng', 'medium', 'vi', true),
('wp_036', 'Việt Nam', 'Hồ Gươm', 'Hồ Tây', 'medium', 'vi', true),
('wp_037', 'Việt Nam', 'Áo dài', 'Áo bà ba', 'medium', 'vi', true),
('wp_038', 'Việt Nam', 'Tết', 'Trung thu', 'easy', 'vi', true),
('wp_039', 'Việt Nam', 'Nón lá', 'Nón bảo hiểm', 'easy', 'vi', true),
('wp_040', 'Việt Nam', 'Bánh chưng', 'Bánh tét', 'easy', 'vi', true),
('wp_041', 'Việt Nam', 'Đà Lạt', 'Sa Pa', 'medium', 'vi', true),
('wp_042', 'Nghề nghiệp', 'Giáo viên', 'Gia sư', 'easy', 'vi', true),
('wp_043', 'Nghề nghiệp', 'Bác sĩ', 'Y tá', 'easy', 'vi', true),
('wp_044', 'Nghề nghiệp', 'Shipper', 'Tài xế Grab', 'easy', 'vi', true),
('wp_045', 'Nghề nghiệp', 'Ca sĩ', 'Rapper', 'medium', 'vi', true),
('wp_046', 'Động vật', 'Mèo', 'Chó', 'easy', 'vi', true),
('wp_047', 'Động vật', 'Cá sấu', 'Thằn lằn', 'medium', 'vi', true),
('wp_048', 'Động vật', 'Voi', 'Hà mã', 'medium', 'vi', true),
('wp_049', 'Thể thao', 'Bóng đá', 'Futsal', 'easy', 'vi', true),
('wp_050', 'Thể thao', 'Cầu lông', 'Tennis', 'easy', 'vi', true),
('wp_051', 'Thể thao', 'Bơi lội', 'Lặn', 'medium', 'vi', true),
('wp_052', 'Trường học', 'Bài tập', 'Kiểm tra', 'easy', 'vi', true),
('wp_053', 'Trường học', 'Thầy cô', 'Hiệu trưởng', 'easy', 'vi', true),
('wp_054', 'Trường học', 'Căn tin', 'Thư viện', 'easy', 'vi', true)
on conflict (id) do update set
  category = excluded.category,
  civilian_word = excluded.civilian_word,
  undercover_word = excluded.undercover_word,
  difficulty = excluded.difficulty,
  language = excluded.language,
  active = excluded.active;
